In [1]:
import pandas as pd


In [2]:
data = pd.read_csv("./mushrooms.csv")


In [3]:
from sklearn import preprocessing


In [4]:
le=preprocessing.LabelEncoder()
for col in data.columns:
    data[col]=le.fit_transform(data[col])

In [5]:
X=data.iloc[:,1:23]
y=data.iloc[:,0]

In [6]:
import numpy as np
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)


In [8]:
scaler = preprocessing.StandardScaler()
X_train=scaler.fit_transform(X_train)

In [9]:
from sklearn import svm
clf = svm.SVC()
clf.fit(X_train, y_train)  

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [10]:
X_test=scaler.fit_transform(X_test)


In [11]:
y_predict=clf.predict(X_test)


In [12]:
from sklearn.metrics import accuracy_score


In [13]:
score=accuracy_score(y_test,y_predict)
print(score)

1.0


In [14]:
clf_linear=svm.LinearSVC()
clf_linear.fit(X_train,y_train)

LinearSVC(C=1.0, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=None, tol=0.0001,
     verbose=0)

In [15]:
y_predict_linear=clf_linear.predict(X_test)


In [16]:
score=accuracy_score(y_test,y_predict_linear)
print(score)

0.9495488105004102


In [17]:
le=preprocessing.LabelEncoder()
for col in data.columns:
    data[col]=le.fit_transform(data[col])

In [18]:
X1=data.iloc[:,1:23]
y1=data.iloc[:,0]

In [19]:
scaler = preprocessing.StandardScaler()
X1=scaler.fit_transform(X1)

In [20]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf_linear2 = svm.LinearSVC( C=0.5)
scores = cross_val_score(clf_linear2, X1, y1, cv=5)
scores 

array([0.67773678, 0.97969231, 0.87815385, 0.99876847, 0.77216749])

In [21]:
from sklearn import svm
from sklearn.model_selection import cross_val_score
clf_linear2 = svm.LinearSVC( C=1)
scores = cross_val_score(clf_linear2, X1, y1, cv=5)
scores 

array([0.69249692, 0.97969231, 0.88      , 0.99876847, 0.7887931 ])

In [22]:
clf_l=svm.SVC(kernel='linear')
clf_l.fit(X1,y1)
scores = cross_val_score(clf_l, X1, y1, cv=5)
scores

array([0.78659287, 1.        , 0.88      , 0.99876847, 0.71982759])

In [23]:
clf_l.coef_


array([[ 4.61767659e-06,  2.12778124e-05, -5.80580993e-05,
         1.04581906e+00, -6.18738416e-01, -5.14392551e-01,
        -3.77326092e+00,  4.59724886e+00, -7.31809389e-05,
        -1.52645945e+00, -5.73314587e+00, -2.96701258e+00,
        -2.79555387e-04,  2.59892899e-07,  1.55546596e-05,
         0.00000000e+00,  4.93552117e+00, -1.15256195e-01,
         4.00442296e+00, -6.93699786e-01, -5.78979515e-01,
         1.24905419e-01]])

In [24]:
clf_nl=svm.SVC()
clf_nl.fit(X1,y1)
scores = cross_val_score(clf_nl, X1, y1, cv=5)
scores

array([0.84255843, 1.        , 0.96061538, 1.        , 0.53140394])

In [25]:
from sklearn.metrics import accuracy_score


In [26]:
import numpy as np
from sklearn.model_selection import train_test_split

In [27]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=.3, random_state=42)

In [28]:
clf_nl=svm.SVC(C=1)
clf_nl.fit(X_train,y_train)
y_pred = clf_nl.predict(X_test)
scores=accuracy_score(y_test,y_pred)
scores

1.0

In [29]:
clf_nl=svm.SVC(C=10,gamma=10,kernel='poly')


clf_nl.fit(X_train,y_train)
y_pred = clf_nl.predict(X_test)
scores=accuracy_score(y_test,y_pred)
scores

1.0